---
title: "050-joins"
author: "Luke Kim"
date: "June 5, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tibble)
library(dplyr)
```

```{r}
x <- tribble(
  ~key, ~val_x,
  1,   "x1",
  2,   "x2",
  3,   "x3"
)
x
```

```{r}
y <- tribble(
  ~key, ~val_y,
  1, "y1",
  2, "y2",
  4, "y3"
)
y
```

```{r}
#by is what you what column you want to join the s and y by
x %>%
    inner_join(y, by = 'key')
```

```{r}
x %>%
    left_join(y, by = 'key') 
```


```{r}
x %>%
   right_join(y, by = 'key') 
```


```{r}
x %>%
    full_join(y, by = 'key') 
```

#many to one or one to many
```{r}
x <- tribble(
  ~key, ~val_x,
  1, "x1",
  2, "x2",
  3, "x3",
  1, "x4",
  1, "x5",
  1, "x6",
  
)
x

y <- tribble(
  ~key, ~val_y,
  1, "y1",
  2, "y2",
  4, "y3"
)
y
```

```{r}
x %>%
    left_join(y, by = 'key')
```


#many to many
```{r}
x <- tribble(
  ~key, ~val_x,
  1, "x1",
  2, "x2",
  3, "x3",
  1, "x4",
  1, "x5",
  1, "x6",
  
)
x

y <- tribble(
  ~key, ~val_y,
  1, "y1",
  2, "y2",
  4, "y3",
  1, "y4",
  1, "y5"
)
y
```


```r
x %>%
    left_join(y, by = 'key')
```

```r
x %>%
    left_join(y, by = c('key', 'col2', 'col3'))

x %>%
    left_join(y, by = c('key' = 'key2', 'col2', 'col3'))
```

