---
title: "datetimes"
author: "Luke Kim"
date: "June 6, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
```

#stringi, stringr packages! will learn later

```{r}
ymd('2018-06-06')
dt_str <- '2018-06-06'
class(dt_str)
```

```{r}
dt_dt <- ymd(dt_str)
class(dt_dt)
```

```{r}
mdy('June 6, 2018')
```

```{r}
dmy('06-06-2018')
```

```{r}
ymd(20190606)
```

```{r}
ymd_hms('2018-06-06 10:33:55', tz = 'etc')
```

```{r}
library(nycflights13)
flight_times <- flights %>%
  select(year, month, day, hour, minute)
```

```{r}
flight_times %>%
  mutate(dep_dt = make_datetime(year, month, day, hour, minute))
```

```{r}
'06-JUNE-18 10:47:30 AM'
```

```{r}
curr_time <- lubridate::as_datetime('WED 06-JUNE-18 10:47:30 AM',
                       format = '%a %d-%B-%y %I:%M:%S %p',
                       tz = "EST")
```

```{r}
now() - curr_time
```
```{r}
library(httr)
git_strings <- GET(url = 'https://raw.githubusercontent.com/bi-sdal/training/master/regex.Rmd')%>%
  content(as = 'text')
write(git_strings,file = 'Regex.RMD')

getwd()
```





